name: Sync .pre-commit-config.yaml and gitleaks folder

on:
  push:
    branches:
      - main

jobs:
  sync-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: sudo apt-get install -y git

    - name: Install Python and Pre-Commit
      run: |
        sudo apt-get install -y python3-pip
        pip3 install pre-commit

    - name: Configure Git user
      run: |
        git config --global user.email "me.choukri1234@gmail.com"
        git config --global user.name "mehdiiix"

    - name: Sync .pre-commit-config.yaml and gitleaks folder to target repositories
      env:
        MEHDI: ${{ secrets.MEHDI }}
        TARGET_REPOS: ${{ secrets.TARGET_REPOS }}
      run: |
        IFS=' ' read -r -a repositories <<< "$TARGET_REPOS"

        for repo in "${repositories[@]}"; do
          git clone "https://$MEHDI@github.com/$repo.git"
          cd "$(basename "$repo")"
          cp ../.pre-commit-config.yaml .pre-commit-config.yaml
          cp -r ../gitleaks gitleaks
          git add .pre-commit-config.yaml gitleaks
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Sync .pre-commit-config.yaml and gitleaks folder from pre-commit-config-repo"
            git push "https://$MEHDI@github.com/$repo.git" HEAD:main
          fi
          cd ..
          rm -rf "$(basename "$repo")"
        done

    - name: Run Pre-Commit
      run: |
        pre-commit install
        pre-commit run --all-files
